# SITE SETTINGS
title: DEMO                        # Title in top navigation bar (navbar) and <head>
author: name                       # Used for copyright statement in footer
url: ""                   
#baseurl: "/pages-guide"                   # Only required if your site is in a directory e.g. https://username.github.io/sitename
                                        # which has url: "https://username.github.io" (no slash) and baseurl: "/sitename" (leading slash)

# SOCIAL PROFILES
social:
  email: name@example.com
  github: github_username               # Can also be a github_username/repository

# THEME SETTINGS (ALL OPTIONAL)
posts_on_home: 3                        # Show x number of latest posts on homepage, can be 0
tweets_on_home: false                    # Show Twitter feed of social.twitter on homepage
archive_permalink: /blog/               # Permalink of page using the archive.html layout, required when using post tags
theme: minima
remote_theme:  peterdesmet/petridish@3.0
github_edit: true                       # Show an "edit this page" link in the footer, can also be name of branch (default: main)
colors:
  links: "#00934a"                      # Color for links: use a readable color that contrasts well with dark text
  banner: "#00934a"                     # Background color for page banners: use color that contrasts well with white
  footer: "#006038"                     # Background color for footer: use color that contrasts well with white
font_serif: true                        # Font type for page content: serif (default) or slightly smaller sans-serif
rounded_corners: true                   # Enable (default) rounded corners on boxes and buttons
logo: /assets/theme/images/logo.png # Logo in navbar, will be displayed with 30px height
languages:
  en: "English"
  fr: "Français"

# BUILD SETTINGS
markdown: kramdown
plugins:                                # If you build your site on gh-pages, only use these plugins: https://pages.github.com/versions/
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - LICENSE
  - package-lock.json
  - package.json
  - petridish.gemspec

# FRONTMATTER DEFAULTS
defaults:
  - scope:
      path: "pages/en"
    values:
      lang: en
      permalink: /:basename/
      layout: default                   # Use default.html layout by default for all files
